language: python
python:
    - "3.5"
    - "3.6"
os:
    - linux
sudo: required
before_install:
    - pip install pytest pytest-cov
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get update
    - sudo apt-get install -y ffmpeg
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - python3 setup.py test
after_success:
    - bash < (curl -s https://codecov.io/bash)
