language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ffmpeg libavcodec-extra-53
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg --with-libvorbis --with-sdl2 --with-theora; fi
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - python3 setup.py test
after_success:
    - coveralls
