language: python
dist: xenial
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
matrix:
  fast_finish: true
  
os:
  - linux
  - osx
matrix:
  # Due to insufficient Python support https://github.com/travis-ci/travis-ci/issues/9929
  allow_failures:
    - os: osx

sudo: required
cache: pip
before_install:
  - pip install pytest pytest-cov codecov
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg --with-libvorbis --with-sdl2 --with-theora; fi
install:
  - pip install -e .
script:
  - python3 setup.py test
after_success:
  - codecov
